namespace DrainService.Dtos
{
    public class GetESMTrackingData_New
    {
        public string? MANDT { get; set; }
        public string? TRACKNO { get; set; }
        public string? ZPOSNR { get; set; }
        public string? CRDATE { get; set; }
        public string? CREATOR { get; set; }
        public string? AUART { get; set; }
        public string? VGBEL { get; set; }
        public string? KUNAG { get; set; }
        public string? KUNNR { get; set; }
        public string? BSTNK { get; set; }
        public string? BSTDK { get; set; }
        public string? VDATU { get; set; }
        public string? UEBTO { get; set; }
        public string? UNTTO { get; set; }
        public string? POSNR { get; set; }
        public string? MATNR { get; set; }
        public string? KWMENG { get; set; }
        public string? VRKME { get; set; }
        public string? UMVKZ { get; set; }
        public string? VRKME1 { get; set; }
        public string? UMVKN { get; set; }
        public string? VRKME2 { get; set; }
        public string? UEPOS { get; set; }
        public string? BWTAR { get; set; }
        public string? VBELN { get; set; }
        public string? CHARG { get; set; }
        public string? SOSTATUS { get; set; }
        public string? BTSTATUS { get; set; }
        public string? Z_BBSNO { get; set; }
        public string? Z_BBS_DEC { get; set; }
        public string? Z_SHAPE_CODE { get; set; }
        public string? Z_SHAPE_SURCHARG { get; set; }
        public string? Z_PROD_DATE { get; set; }
        public string? Z_INV_LEN { get; set; }
        public string? Z_NO_OF_BEND_PC { get; set; }
        public string? Z_NO_OF_CUT_PC { get; set; }
        public string? Z_NO_ROLLING_PC { get; set; }
        public string? Z_PIECES { get; set; }
        public string? LOCATION { get; set; }
        public string? REMARKS { get; set; }
        public string? SITECON { get; set; }
        public string? Z_CW_DIA { get; set; }
        public string? Z_CW_LEN { get; set; }
        public string? Z_CW_OVR_HANG1 { get; set; }
        public string? Z_CW_OVR_HANG2 { get; set; }
        public string? Z_CW_SPA { get; set; }
        public string? Z_ELEM_TYPE { get; set; }
        public string? Z_MW_DIA { get; set; }
        public string? Z_MW_LEN { get; set; }
        public string? Z_MW_OVR_HANG1 { get; set; }
        public string? Z_MW_OVR_HANG2 { get; set; }
        public string? Z_MW_SPA { get; set; }
        public string? Z_PROD_MARK { get; set; }
        public string? Z_WBS1 { get; set; }
        public string? Z_WBS2 { get; set; }
        public string? Z_WBS3 { get; set; }
        public string? Z_WBS4 { get; set; }
        public string? Z_WBS5 { get; set; }
        public string? Z_MAC_NO { get; set; }
        public string? Z_NO_OF_PNT { get; set; }
        public string? Z_NO_OF_STR { get; set; }
        public string? Z_TOTAL_BEND { get; set; }
        public string? Z_TOTAL_CUT { get; set; }
        public string? BAR_MARK { get; set; }
        public string? NO_MW_PC { get; set; }
        public string? NO_CW_PC { get; set; }
        public string? ACT_MW_LEN { get; set; }
        public string? ACT_CW_LEN { get; set; }
        public string? Z_LGY_CODE { get; set; }
        public string? SLOPE { get; set; }
        public string? BENDING_PIN { get; set; }
        public string? SEG_A { get; set; }
        public string? SEG_B { get; set; }
        public string? SEG_C { get; set; }
        public string? SEG_D { get; set; }
        public string? SEG_E { get; set; }
        public string? SEG_F { get; set; }
        public string? SEG_G { get; set; }
        public string? SEG_H { get; set; }
        public string? SEG_I { get; set; }
        public string? SEG_J { get; set; }
        public string? SEG_K { get; set; }
        public string? SEG_L { get; set; }
        public string? SEG_M { get; set; }
        public string? SEG_N { get; set; }
        public string? SEG_O { get; set; }
        public string? SEG_R { get; set; }
        public string? SEG_S { get; set; }
        public string? SEG_T { get; set; }
        public string? HT_H { get; set; }
        public string? AN_P { get; set; }
        public string? AN_Q { get; set; }
        public string? AN_R { get; set; }
        public string? AN_S { get; set; }
        public string? AN_T { get; set; }
        public string? AN_U { get; set; }
        public string? AN_V { get; set; }
        public string? AN_W { get; set; }
        public string? HT_B { get; set; }
        public string? HT_C { get; set; }
        public string? HT_D { get; set; }
        public string? LEG { get; set; }
        public string? HOOK { get; set; }
        public string? T_MW_TYPE { get; set; }
        public string? T_CW_TYPE { get; set; }
        public string? T_THEO_KG { get; set; }
        public string? T_NET_KG { get; set; }
        public string? T_BOM { get; set; }
        public string? T_MWOH1 { get; set; }
        public string? T_MWSP { get; set; }
        public string? T_MWPC { get; set; }
        public string? T_CWPC { get; set; }
        public string? T_CWSP { get; set; }
        public string? T_MHOH2 { get; set; }
        public string? T_CWOH1 { get; set; }
        public string? T_CWOH2 { get; set; }
        public string? T_REVERSE { get; set; }
        public string? T_COMBINE { get; set; }
        public string? T_FORCE { get; set; }
        public string? T_PTCM01 { get; set; }
        public string? T_PTCM02 { get; set; }
        public string? T_PTCM03 { get; set; }
        public string? T_PTCM04 { get; set; }
        public string? T_PTCM05 { get; set; }
        public string? T_PTCM06 { get; set; }
        public string? T_PTCM07 { get; set; }
        public string? T_PTCM08 { get; set; }
        public string? T_PTCM09 { get; set; }
        public string? T_PTCM10 { get; set; }
        public string? T_PTCC01 { get; set; }
        public string? T_PTCC02 { get; set; }
        public string? T_PTCC03 { get; set; }
        public string? T_PTCC04 { get; set; }
        public string? T_PTCC05 { get; set; }
        public string? T_PTCC06 { get; set; }
        public string? T_PTCC07 { get; set; }
        public string? T_PTCC08 { get; set; }
        public string? T_PTCC09 { get; set; }
        public string? T_PTCC10 { get; set; }
        public string? T_DEL_DIR { get; set; }
        public string? T_DEL_DIS { get; set; }
        public string? T_DEL_TIME { get; set; }
        public string? T_CAB_PROD_LEN { get; set; }
        public string? T_CUT_TIME { get; set; }
        public string? T_BEND_TIME { get; set; }
        public string? T_STK_TIME { get; set; }
    }
}
